apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: MYSQL_USER_NAME
              optional: false
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: MYSQL_ROOT_PASSWORD
              optional: false
        ports:
        - containerPort: 3306
          name: mysql
