apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: alpine
    command: ["sleep","3600"]
    env:
    - name: player_initial_lives
      valueFrom:
        configMapKeyRef:
          name: game-demo
          key: player_initial_lives
