apiVersion: v1
kind: Pod
metadata:
  name: database1
  labels:
    app: database1
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-check
            key: rootPassword
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: secret-check
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret-check
            key: password
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: secret-check
            key: database